name: Hello World
description: Greet someone
inputs:
  name:
    description: Name
    required: true
runs:
  using: composite
  steps:
    - run: echo "Hello ${{ inputs.name }}"
      shell: bash
    - shell: bash
      run: echo "${{ github.actior }}/${{ github.repository }}/${{ secrets.GITHUB_TOKEN }}"
