name: ci
on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno install -qAn vr https://deno.land/x/velociraptor@1.5.0/cli.ts

      - run: |
          echo $GITHUB_PATH
          echo $PATH
          vr --version
