name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test
        run: echo "This is Test!!"

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -d '{ "event_type": "deploy" }' \
            -i 'https://api.github.com/repos/shun-shobon/tmp/dispatches'

